version: "3.9"

networks:
  jib-jab-postgres:
    external: true

services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prod_db
    ports:
      - "5432:5432"
    networks:
      - jib-jab-postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - jib-jab-postgres
    ports:
      - "5050:80"